version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static:/app/staticfiles
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 myportal.asgi:application"

volumes:
  static: